### ISSUE TITLE
Reps testing

### ISSUE THREAD

**Issue by gaby2300** [MichaelKohler/content-queue-test#11]
## Tweet should be about
Mozilla

## Tweet Content
Scheduled tweet

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.,
 - Date can not be parsed. Please follow the format of DD.MM.YYYY HH:mm

**Comment by gaby2300** [comment]
Hello Michael, I edited the issue adding the required. I hope it's correct now!

**Comment by MichaelKohler** [comment]
@gaby2300 the section "Tweet Content" should be the tweet itself, not *todo*

**Comment by gaby2300** [comment]
@MichaelKohler , I added "Firefox new features" in place of "todo" Is it correct now?

**Comment by gaby2300** [comment]
@MichaelKholer, Yes, I replaced "todo" with Firefox new features" I hope
it's all correct now! Thanks

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.,
 - Date can not be parsed. Please follow the format of DD.MM.YYYY HH:mm

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.,
 - Date can not be parsed. Please follow the format of DD.MM.YYYY HH:mm

**Comment by gaby2300** [comment]
@MichaelKohler  I am sorry, it seems I don't understand how  to do this correctly. 
I changed "Tweet should be about" for "Mozilla", I replaced "todo" with "Firefox new features" and I scheduled for 01.09.2017 12:00.
If you could please tell me what is wrong so I can fix it, I would greatly appreciate it!

**Comment by freaktechnik** [comment]
See the issue I referenced earlier in this thread. Something is wrong with the caching here. Also note that the michael kohler posting the errors here is actually the tool that is running under his account.

**Comment by MichaelKohler** [comment]
I'll keep this open so we can debug it.

**Comment by MichaelKohler** [comment]
Looks like the fix from @freaktechnik is good :) I'm approving this one and then it should get tweeted.

**Comment by MichaelKohler** [comment]
Successfully tweeted. See https://twitter.com/reps_cq_test/status/907307425866420224
