### ISSUE TITLE
Mention by onlygan

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/content-queue-test#12]
## Tweet should be about
Prepare a reply for the request by the user onlygan:
> [@reps\_cq\_test](https://twitter.com/reps_cq_test "Michael - Reps test") [@onlygan](https://twitter.com/onlygan "S S Pillai")

## Tweet Content
hi there! :)

## Reply to
https://twitter.com/onlygan/status/903541505201020928

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by MichaelKohler** [comment]
:warning: **Some actions have to be taken before this tweet is ready:**

 - Tweet content is just a placeholder. Please replace it with the actual content for the tweet.

**Comment by freaktechnik** [comment]
Let's see if at least the closed state propagates
