### ISSUE TITLE
Retweet example

### ISSUE THREAD

**Issue by freaktechnik** [MichaelKohler/content-queue-test#5]
## Tweet should be about
A retweet example for @Mte90. Instead of the "Tweet Content" section there is a "Retweet" section.

## Retweet
https://twitter.com/reps_cq_test/status/901226816916127745

**Comment by Mte90** [comment]
Uhm an account can retweet itself?

**Comment by freaktechnik** [comment]
Yes, since some time now. This also lets you show @ replies to all your followers, which was the main reason it was added.

**Comment by Mte90** [comment]
Oh cool I miss that!
Ok let's see what happen :-)

**Comment by freaktechnik** [comment]
Well, nothing will happen as long as it's in the ideas column.

**Comment by MichaelKohler** [comment]
Successfully retweeted.

**Comment by MichaelKohler** [comment]
Just moved it (and also actually invited all Council to the repo so they can all move as well)
